#!/bin/bash
#PBS -N vasp_serial
#PBS -l nodes=1:ppn=48
#PBS -q kgz48
#PBS -V
#PBS -S /bin/bash
### Set intel environment###
module load hdf5
module load gcc/9.3.0
source /public/software/intel2020u2/intel2020u2_env.sh

start_time=$(date +"%Y-%m-%d %H:%M:%S")
cd $PBS_O_WORKDIR

# 获取所有子目录
#task_dirs=($(find . -mindepth 1 -maxdepth 1 -type d))
task_dirs=(
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M1/Au"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M1/Ag"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M1/Cu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M1/Pd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AuAu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AuAg"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AuCu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AuPd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AgAg"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AgCu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/AgPd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/CuCu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/CuPd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M2/PdPd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAuAu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAuAg"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAuCu"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAuPd"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAgAg"
"/public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/M3/AuAgCu"
)
#command="echo hello 1>out 2>err"
command="mpirun -np $(cat $PBS_NODEFILE | wc -l) /public/software/vasp.6.3.2-x/bin/vasp_std_x 1>out 2>err"
freq_fix=0

# 设置任务数量
num_tasks=${#task_dirs[@]}

# 任务监控
energy_path=$(if [ -f "energy.txt" ]; then echo "new_energy.txt"; else echo "energy.txt"; fi)
rm new_energy.txt running_job completed_job
echo "species        energy            force" > $energy_path

for ((i=0; i<$num_tasks; i++)); do
    task_dir=${task_dirs[$i]}

    ####################### run ########################
    cd $task_dir                                       #
    /public/home/sl/scripts/pos2pot    
    cp /public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/INCAR .
    cp /public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/KPOINTS .
    cp /public/home/sl/work/DFT_work/SL/M@C3N4/notebook/github/Computational-Chemistry/project/M@g-C3N4/slab/OPTCELL .
    echo $(i+1) $(pwd) > $PBS_O_WORKDIR/running_job    #
    eval "$command"                                    #
    #/public/home/sl/scripts/mk_pwdfreq.sh              #
    #cd freq                                            #
    #/public/home/sl/scripts/fix_slab.py "$freq_fix"    #
    #eval "$command"                                    #
    #cd ..                                              #
    ####################################################

    echo $(i+1) $(pwd) >> $PBS_O_WORKDIR/completed_job
    bash /public/home/sl/scripts/ta.sh | awk '{print $1 "          " $13 "     " $10}' | tail -2 | head -1  >> $PBS_O_WORKDIR/$energy_path
    # 返回上一级目录
    cd ..
done

end_time=$(date +"%Y-%m-%d %H:%M:%S")
start_seconds=$(date -d "$start_time" +%s)
end_seconds=$(date -d "$end_time" +%s)
elapsed_seconds=$((end_seconds - start_seconds))
elapsed_minutes=$(echo "scale=1; $elapsed_seconds / 60" | bc)"min"

echo $(date) $PBS_JOBID $USER $PBS_JOBNAME $PBS_O_WORKDIR $elapsed_minutes >> ~/mail

